version: "2"
services:
  drupal:
    build:
      context: .
      
    image: custom-drupal
    ports:
      - "8080:80"
    volumes:
      - modules:/var/www/html/modules
      - themes:/var/www/html/themes
      - profiles:/var/www/html/profiles    
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
    volumes:
      - drupal-data:/var/lib/postgresql/data
volumes:
  modules:
  themes:
  profiles:
  drupal-data:  
